Notebook to test on real data

In [1]:
import numpy as np
import pandas as pd
import duckdb as duckdb

import psutil, os

from datkit.cleaning import clean_dataframe

In [2]:
p = psutil.Process(os.getpid())

psutil.virtual_memory().available / 1024 / 1024    # headroom on the machine

6557.08984375

In [11]:
p.memory_info().rss    / 1024 / 1024                 # what this process holds right now

1824.33203125

In [9]:
p.memory_info().peak_wset  / 1024 / 1024             # Windows only: high-water mark

1917.13671875

Import table

In [3]:
# don't use dtype=str as that creates legacy objects that pythons stores strings in
# pyarrow is a better option for string storage and manipulation (columnar storage)
df_title_basics = pd.read_csv(
    "d:/dev/data-analysis-toolkit/devdata/title.basics.tsv.gz", sep="\t", dtype_backend="pyarrow", nrows=1000_000
)

df_title_akas = pd.read_csv(
    "d:/dev/data-analysis-toolkit/devdata/title.akas.tsv.gz", sep="\t", dtype_backend="pyarrow"
)

In [2]:

df_title_ratings = pd.read_csv(
    "d:/dev/data-analysis-toolkit/devdata/title.ratings.tsv.gz", sep="\t", dtype_backend="pyarrow"
)

In [ ]:
#try some data conversion

df_title_ratings.sample(n=5,random_state=1)

            tconst  averageRating  numVotes
1544457  tt6464184            6.8       290
26936    tt0044583            5.4        66
922261   tt1986692            8.1        17
1705361  tt9769820            8.2        56
462316   tt0953069            7.8        16

## clean table

In [26]:
df_title_basics.sample(n=5, random_state=1)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
276826,tt0289439,video,Scrotal Vengeance,Scrotal Vengeance,0,2001,\N,\N,\N
849425,tt0877822,tvEpisode,Episode #1.738,Episode #1.738,0,1969,\N,30,"Drama,Fantasy,Horror"
504499,tt0525484,tvEpisode,"Murder, What Murder?","Murder, What Murder?",0,1999,\N,50,"Crime,Drama,Mystery"
601054,tt0623502,tvEpisode,Episode dated 7 August 2001,Episode dated 7 August 2001,0,2001,\N,\N,Game-Show
980221,tt1002392,tvEpisode,Episode dated 7 November 2006,Episode dated 7 November 2006,0,2006,\N,\N,News

In [27]:
df_title_ratings.sample(n=5, random_state=1)

            tconst  averageRating  numVotes
1544457  tt6464184            6.8       290
26936    tt0044583            5.4        66
922261   tt1986692            8.1        17
1705361  tt9769820            8.2        56
462316   tt0953069            7.8        16

In [28]:
df_title_basics, title_basics_cleaning_report = clean_dataframe(df_title_basics, True)

In [29]:
df_title_ratings, title_ratingscleaning_report = clean_dataframe(df_title_ratings, True)

In [30]:
df_title_basics.sample(n=5, random_state=1)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
276826,tt0289439,video,Scrotal Vengeance,Scrotal Vengeance,0,2001,<NA>,<NA>,<NA>
849425,tt0877822,tvEpisode,Episode #1.738,Episode #1.738,0,1969,<NA>,30,"Drama,Fantasy,Horror"
504499,tt0525484,tvEpisode,"Murder, What Murder?","Murder, What Murder?",0,1999,<NA>,50,"Crime,Drama,Mystery"
601054,tt0623502,tvEpisode,Episode dated 7 August 2001,Episode dated 7 August 2001,0,2001,<NA>,<NA>,Game-Show
980221,tt1002392,tvEpisode,Episode dated 7 November 2006,Episode dated 7 November 2006,0,2006,<NA>,<NA>,News

In [31]:
title_basics_cleaning_report

,column,dtype_before,dtype_after,converted,bytes_before,bytes_after,bytes_saved,mb_before,mb_after,mb_saved,nulls_before,nulls_after,nulls_created
0,tconst,string[pyarrow],string[pyarrow],False,13026881,13151881,-125000,12.42,12.54,-0.12,0,0,0
1,titleType,string[pyarrow],string[pyarrow],False,11188148,11313148,-125000,10.67,10.79,-0.12,0,0,0
2,primaryTitle,string[pyarrow],string[pyarrow],False,22754490,22879490,-125000,21.70,21.82,-0.12,0,0,0
3,originalTitle,string[pyarrow],string[pyarrow],False,22776956,22901956,-125000,21.72,21.84,-0.12,0,0,0
4,isAdult,int64[pyarrow],int64[pyarrow],False,8000000,8000000,0,7.63,7.63,0.00,0,0,0
5,startYear,string[pyarrow],int64[pyarrow],True,7988284,8125000,-136716,7.62,7.75,-0.13,0,5858,5858
6,endYear,string[pyarrow],int64[pyarrow],True,6050772,8125000,-2074228,5.77,7.75,-1.98,0,974614,974614
7,runtimeMinutes,string[pyarrow],int64[pyarrow],True,6039904,8125000,-2085096,5.76,7.75,-1.99,0,389486,389486
8,genres,string[pyarrow],string[pyarrow],False,15744880,15749092,-4212,15.02,15.02,-0.00,0,60394,60394

In [32]:
df_title_ratings.sample(n=5, random_state=1)

            tconst  averageRating  numVotes
1544457  tt6464184            6.8       290
26936    tt0044583            5.4        66
922261   tt1986692            8.1        17
1705361  tt9769820            8.2        56
462316   tt0953069            7.8        16

In [33]:
title_ratingscleaning_report

,column,dtype_before,dtype_after,converted,bytes_before,bytes_after,bytes_saved,mb_before,mb_after,mb_saved,nulls_before,nulls_after,nulls_created
0,tconst,string[pyarrow],string[pyarrow],False,22763052,22976955,-213903,21.71,21.91,-0.2,0,0,0
1,averageRating,double[pyarrow],double[pyarrow],False,13689792,13689792,0,13.06,13.06,0.0,0,0,0
2,numVotes,int64[pyarrow],int64[pyarrow],False,13689792,13689792,0,13.06,13.06,0.0,0,0,0

In [34]:
df_title_ratings["tconst"].nunique()

1711224

In [35]:
df_title_basics["tconst"].nunique()

1000000

## Explore

In [36]:
# Merge using duckdb

df_title_basics = duckdb.sql(
    """ 
    select 
        a.*, b.averageRating, b.numVotes
    from 
        df_title_basics a
        left join
        df_title_ratings b
        on
            a.tconst = b.tconst
    """
    ).df()

In [21]:
# Merge using pandas merge

df_title_basics = df_title_basics.merge(df_title_ratings[['averageRating', 'numVotes','tconst']], on='tconst', how='left')

In [46]:
df_title_basics.sample(n=5, random_state=1)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes,tooOld,hasRating
276826,tt0475351,short,Opera Baby,Opera Baby,0,2005.0,NaN,3.0,"Comedy,Short",NaN,NaN,False,False
849425,tt0927940,tvEpisode,Ui-ui-ui oder Die Verwandlung der Energie,Ui-ui-ui oder Die Verwandlung der Energie,0,1983.0,NaN,NaN,Drama,NaN,NaN,True,False
504499,tt0235631,movie,Wet Lust: 21 Strippers,Nureta yokujô: Tokudashi 21-nin,0,1974.0,NaN,77.0,"Comedy,Drama",6.8,53.0,True,True
601054,tt0606283,tvEpisode,Episode dated 3 February 2001,Episode dated 3 February 2001,0,2001.0,NaN,45.0,Talk-Show,NaN,NaN,False,False
980221,tt0997102,movie,SuperWizja,SuperWizja,0,1993.0,NaN,83.0,"Mystery,Sci-Fi",5.5,24.0,True,True

In [44]:
# Create flags for conditions

df_title_basics["tooOld"] = df_title_basics["startYear"] < 2000
df_title_basics["hasRating"] = df_title_basics["averageRating"].notna()

In [45]:
df_title_basics.groupby(['titleType']).agg(
    all_records=('tconst', 'count'),
    distinct_keys=('tconst', 'nunique'),
    Numtooold=('tooOld', 'sum'),
    Numwrating=('hasRating', 'sum'),
)

              all_records  distinct_keys  Numtooold  Numwrating
titleType
movie              226294         226294     190326      152153
short              139792         139792     104722       51770
tvEpisode          467210         467210     244857      182416
tvMiniSeries         6149           6149       4177        4549
tvMovie             45395          45395      30782       26315
tvSeries            44349          44349      27746       27699
tvShort              2004           2004       1239         904
tvSpecial            6755           6755       3349        3977
video               56702          56702      23204       24705
videoGame            5350           5350       2847        4754

In [18]:
duckdb.sql(
    """ 
    select 
        titleType, avg(isAdult) average_Adult
    from 
        df_title_basics
    group by
        titleType
    """
    ).show()

┌──────────────┬───────────────────────┐
│  titleType   │     average_Adult     │
│   varchar    │        double         │
├──────────────┼───────────────────────┤
│ tvMovie      │    0.0005577352104008 │
│ short        │  0.002432588902860001 │
│ tvSpecial    │ 0.0006018456600240739 │
│ videoGame    │  0.049801393241382066 │
│ video        │   0.34985629795734574 │
│ tvShort      │ 0.0002714440825190011 │
│ movie        │  0.012029918090235627 │
│ tvPilot      │                   0.0 │
│ tvSeries     │  0.010280220501378133 │
│ tvEpisode    │   0.03503159613674168 │
│ tvMiniSeries │ 0.0066859265373503925 │
├──────────────┴───────────────────────┤
│ 11 rows                    2 columns │
└──────────────────────────────────────┘

In [ ]:
df_title_basics_clean.shape()

In [ ]:
def sample_records(df: pd.DataFrame, n=10000, seed=1) -> pd.DataFrame:
    """Return a sample of records from the DataFrame."""
    if len(df) > n:
        return df.sample(n=n, random_state=seed)
    else:
        return df

In [ ]:
df_clean_sample = sample_records(df_clean)

In [ ]:
df_sample_nonunique = df_clean_sample.nunique()

In [ ]:
df_sample_nonunique.iloc[2]

np.int64(9835)

In [ ]:
df_sample_nonunique["isAdult"]

np.int64(2)

In [ ]:
cleaning_report[cleaning_report["column"] == "isAdult"]["dtype_after"].values[0]

'int64[pyarrow]'

for col in df_clean_sample.columns:
    if df_sample_nonunique[col] > 100:
        if "string" in cleaning_report[cleaning_report["column"] == col]["dtype_after"].values[0]:
            pass
        else:
            df_clean_sample[col] = pd.cut(df_clean_sample[col], bins=5)
    elif df_sample_nonunique[col] > 10:
    else:

def binning(s:pd.Series) -> pd.Series:

In [ ]:
df_clean_sample["runtimeMinutes_bins"] = pd.cut(df_clean_sample["runtimeMinutes"], bins=10)

In [ ]:
df_clean_sample.groupby("runtimeMinutes_bins", observed=False)["runtimeMinutes"].agg(["count", "min", "max", "mean", "median", "std"])

                     count   min   max        mean  median        std
runtimeMinutes_bins
(-0.427, 143.7]       8549     1   143   74.047023    83.0   30.93211
(143.7, 286.4]         178   144   282  187.747191   177.5  35.500905
(286.4, 429.1]          33   288   420  335.606061   320.0  41.296897
(429.1, 571.8]           3   476   540       512.0   520.0  32.741411
(571.8, 714.5]           1   624   624       624.0   624.0       <NA>
(714.5, 857.2]           1   763   763       763.0   763.0       <NA>
(857.2, 999.9]           0  <NA>  <NA>        <NA>    <NA>       <NA>
(999.9, 1142.6]          0  <NA>  <NA>        <NA>    <NA>       <NA>
(1142.6, 1285.3]         0  <NA>  <NA>        <NA>    <NA>       <NA>
(1285.3, 1428.0]         1  1428  1428      1428.0  1428.0       <NA>

In [ ]:
series_nona = df_clean_sample["runtimeMinutes"].dropna()
low, high = np.percentile(series_nona, [1,99]) # does not accept NA values
print(low, high)

6.0 210.0

In [ ]:
arrasy_sample = np.array([1,2,2,3,4,4,4,5,5,6,6,7,7,8])
np.unique(arrasy_sample)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
binresult = bin_column(df_clean_sample["titleType"], tail_min_span=0.3)
binresult

TypeError: bin_categorical() got an unexpected keyword argument 'tail_min_span'

In [ ]:
binresult

       region   left   right  count    pct
0    low_tail    1.0     3.0     32   0.37
1        core    3.0    29.2   1035  11.81
2        core   29.2    55.4    883  10.07
3        core   55.4    81.6   2156  24.60
4        core   81.6   107.8   3731  42.56
5        core  107.8   134.0    639   7.29
6        core  134.0   160.2    124   1.41
7        core  160.2   186.4     55   0.63
8        core  186.4   212.6     26   0.30
9        core  212.6   238.8     22   0.25
10       core  238.8   265.0     20   0.23
11  high_tail  265.0  1428.0     43   0.49